### PR TITLE
Output maf version number with "--mafversion"

### PR DESCRIPTION
**Pull request by hiroshinoji**
Incomplete implementation for #89.

Currently maf.py obtain the revision number of git, but now maflib cannot access to it.
We have to implement core.ExpOptionsContext.**init**. The version is now a constant of in maf.py, but we cannot access this number from maflib. Maybe we have to make an auto generated file in .waf-*/maflib directory to save some constants.

### CODE REVIEW

**Comment by hiroshinoji** [comment]
Currently it is partly working but not complete.

To check version numbers, `core.py` has constants `MAFVERSION` and `MAFREVISION` which are inserted by `generate_maf.py`. These versions are checked in `maf.py` when loading. `generate_maf.py` also assigns version numbers to `maf.py` so these should be consistent.

The current problem is, when using maf in the git repository (where `maflib` exist) `core.py` is loaded from not hidden directory (`.waf-.../maflib`) but the `maflib`directory. The original `maflib/core.py` doesn't have version numbers so it cannot load version numbers correctly.

**Comment by hiroshinoji** [comment]
The problem above is rather complicated. First, I found a snippet in waflib where `sys.path` is written temporarily during executing main waf logic:
http://docs.waf.googlecode.com/git/apidocs_17/_modules/waflib/Context.html#load_module

For this, when loading `maf.py`, `maflib/core.py` has a precedence over `.waf-*/maflib/core.py`.

We skip this problem by not checking version in `maf.py` if the user is probably developing maflib. If the loaded version is not filled, that means `maflib` is loaded from the current directory, in that case we assume the user is developing maflib.

**Comment by beam2d** [comment]
Thanks for supporting versioning. LGTM with one comment.

If one migrates from old version that does not define MAFVERSION to the new version with MAFVERSION, an exception `AttributeError: 'module' object has no attribute 'MAFVERSION'` occurs. It should be more verbose (e.g. catch it and print some verbose message).

**Comment by beam2d** [comment]
LGTM!

**Pull request merged**
